//
// Created by deffrian on 22.04.22.
//

#ifndef LATTICE_AGREEMENT_GENERALIZED_LATTICE_AGREEMENT_H
#define LATTICE_AGREEMENT_GENERALIZED_LATTICE_AGREEMENT_H

#endif //LATTICE_AGREEMENT_GENERALIZED_LATTICE_AGREEMENT_H
